server:
  port: 8094

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tsmahur/configurations-server
          clone-on-start: true